// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: userDetails.sql

package db

import (
	"context"
	"database/sql"
)

const createUserDetail = `-- name: CreateUserDetail :one

INSERT INTO
    user_details (user_id, photo, address)
VALUES ($1, $2, $3) RETURNING id, user_id, photo, address, created_at
`

type CreateUserDetailParams struct {
	UserID  string         `json:"user_id"`
	Photo   sql.NullString `json:"photo"`
	Address sql.NullString `json:"address"`
}

func (q *Queries) CreateUserDetail(ctx context.Context, arg CreateUserDetailParams) (UserDetail, error) {
	row := q.db.QueryRowContext(ctx, createUserDetail, arg.UserID, arg.Photo, arg.Address)
	var i UserDetail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Photo,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}
